command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: ENV
    value: "production"
  - name: PORT
    value: "8000"
  - name: DEBUG
    value: "False"

resources:
  cpu: "1"
  memory: "2Gi"

description: "React + FastAPI application with MUI and Framer Motion"
